{% set name = "pyxel-sim" %}
{% set version = "2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyxel_sim-{{ version }}.tar.gz
  sha256: f742beeddd36f7cda3ffb6165d105ac662dfd44418b21792105302738b1a8080

build:
  entry_points:
    - pyxel = pyxel.run:main
    - pyxel-sim = pyxel.run:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.10,<3.14
    - setuptools >=77
    - versioneer ==0.29
    - wheel
    - pip
  run:
    - python >=3.10,<3.14
    - numpy >=2
    - scipy >=1.12
    - pandas >=2.1,<3
    - xarray >=2024.10.0
    - astropy >=5.2
    - astroquery <0.4.11
    - specutils >=1.2
    - synphot
    - scikit-image >=0.23.0
    - numba >=0.56.4
    - hvplot >=0.9
    - fsspec >=2021
    - pympler
    - pillow
    - diskcache
    - rich
    - asdf # Added manually
    - pygmo  >=2.16.1 # Added manually
    - poppy # Added manually
    - panel # Added manually
    - pooch # Added manually

test:
  imports:
    - pyxel
    - pyxel.calibration
  commands:
    - pip check
    - pyxel --help
    - pyxel-sim --help
  requires:
    - pip

about:
  home: https://esa.gitlab.io/pyxel/
  summary: Pyxel detector simulation framework.
  dev_url: https://gitlab.com/esa/pyxel
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flemmel
