{% set name = "pyxel-sim" %}
{% set version = "1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyxel_sim-{{ version }}.tar.gz
  sha256: d168993eb51e552bdff72c6d4954553c444e73771e3252f07af10e6b166ccb4c

build:
  number: 0
  noarch: python
  entry_points:
    - pyxel = pyxel.run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=40.1
    - wheel >=0.29.0
    - versioneer
  run:
    - astropy >=4.3
    - attrs >=21.3.0
    - bokeh
    - dask-core
    - distributed
    - fsspec >=2021
    - h5py
    - holoviews >=1.15.0
    - ipywidgets >=7.5
    - matplotlib-base >=3.1
    - numba
    - numpy >=1.20
    - openpyxl
    - pandas
    - pillow
    - pympler
    - pyyaml
    - scikit-image
    - scipy
    - seaborn
    - tqdm
    - typing-extensions
    - xarray >=0.19
    - xlrd
    - pygmo       # Added manually
    - netcdf4

test:
  imports:
    - pyxel
    - pyxel.calibration
  commands:
    - pip check
    - pyxel --help
  requires:
    - pip

about:
  home: https://esa.gitlab.io/pyxel/
  summary: Pyxel detector simulation framework.
  dev_url: https://gitlab.com/esa/pyxel
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flemmel
    - constanzeseibert
