{% set version = "3.0" %}

package:
  name: pyxel-sim
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyxel-sim/pyxel_sim-{{ version }}.tar.gz
  sha256: 9db1718ab26eb994117df70228d40a93a9d9383c45be41a1c6639604f8357920

build:
  skip: true  # [py<310]
  entry_points:
    - pyxel = pyxel.run:main
    - pyxel-sim = pyxel.run:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=77
    - versioneer ==0.29
    - wheel
    - pip
  run:
    - python >=3.10
    - numpy >=2
    - scipy >=1.14
    - pandas >=2.3
    - xarray >=2024.10.0
    - astropy >=5.2
    - astroquery  # [not emscripten]
    - specutils >=1.2  # [not emscripten]
    - synphot  # [not emscripten]
#    - pyckles  # [not emscripten]
    - scikit-image >=0.24.0
    - numba >=0.56.4  # [not emscripten]
    - hvplot >=0.9  # [not emscripten]
    - matplotlib-base
    - seaborn  # [not emscripten]
    - datashader  # [not emscripten]
    - fsspec >=2021
    - h5py
    - attrs
    - typing_extensions
    - click
    - toolz
    - pooch
    - pympler
    - pillow
    - diskcache
    - rich
    - annotated-types
    - asdf # Added manually
    - pygmo  >=2.16.1 # Added manually
    - poppy # Added manually
    - panel # Added manually
    - dask  # Added manually
    - pooch # Added manually

test:
  imports:
    - pyxel
    - pyxel.calibration
  commands:
#    - pip check
    - pyxel --help
    - pyxel-sim --help
  requires:
    - pip

about:
  home: https://esa.gitlab.io/pyxel/
  summary: Pyxel detector simulation framework.
  dev_url: https://gitlab.com/esa/pyxel
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flemmel
