{% set name = "pyxel-sim" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyxel-sim-{{ version }}.tar.gz
  sha256: 7d24d252c0e2a343d97782e8149a564bacd3b189b453b81915873d05f7e2c002

build:
  number: 0
  noarch: python
  entry_points:
    - pyxel = pyxel.run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=40.1
    - wheel >=0.29.0
  run:
    - astropy >=4.3
    - bokeh
    - click
    - dask-core
    - distributed
    - fsspec >=2021
    - h5py
    - holoviews >=1.14.2
    - ipywidgets >=7.5
    - jupyterlab
    - matplotlib-base >=3.1
    - notebook
    - numba
    - numpy >=1.20
    - openpyxl
    - pandas
    - panel >=0.12.7
    - pillow
    - pympler
    - python >=3.7
    - pyyaml
    - scikit-image
    - scipy
    - seaborn
    - tqdm
    - typing-extensions
    - xarray >=0.19
    - xlrd
    - pygmo
    - netcdf4

test:
  imports:
    - pyxel
    - pyxel.calibration
  commands:
    - pip check
    - pyxel --help
  requires:
    - pip

about:
  home: https://esa.gitlab.io/pyxel/
  summary: Pyxel detector simulation framework.
  dev_url: https://gitlab.com/esa/pyxel
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flemmel
