{% set name = "pyxel-sim" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyxel_sim-{{ version }}.tar.gz
  sha256: 5d5463c59a883781b5abdfba16dc6b0cc888507f62ba2d60339ed86b02d0042c

build:
  entry_points:
    - pyxel = pyxel.run:main
    - pyxel-sim = pyxel.run:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=63
    - versioneer ==0.29
    - wheel
    - pip
  run:
    - python >=3.9
    - numba >=0.56.4
    - numpy >=1.24
    - pandas >=1.5
    - scipy >=1.10
    - xarray >=2023.12.0,<2024.9.0
    - xarray-datatree >=0.0.12
    - sep
    - matplotlib-base >=3.6
    - seaborn
    - hvplot >=0.9
    - bokeh >=3.3.0
    - panel
    - dask-core
    - distributed
    - ipywidgets >=7.5
    - astropy >=4.3
    - fsspec >=2021
    - aiohttp
    - h5netcdf
    - pyyaml
    - xlrd
    - openpyxl
    - attrs >=21.3.0
    - click !=8.1.4,!=8.1.5
    - tqdm
    - typing-extensions >=4.5
    - pympler
    - pillow
    - scikit-image >=0.20.0
    - astroquery
    - specutils
    - synphot
    - diskcache
    - rich
    - asdf # Added manually
    - pygmo  >=2.16.1 # Added manually
    - poppy # Added manually
    - panel # Added manually


test:
  imports:
    - pyxel
    - pyxel.calibration
  commands:
    - pip check
    - pyxel --help
    - pyxel-sim --help
  requires:
    - pip

about:
  home: https://esa.gitlab.io/pyxel/
  summary: Pyxel detector simulation framework.
  dev_url: https://gitlab.com/esa/pyxel
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flemmel
